### ISSUE TITLE
Remove Button on the Update Page

### ISSUE THREAD

**Issue by danieliheonu** [bubbl-oss/evoting#19]
The remove button doesn't have any function on the update page and shouldn't be there since the delete button removes the candidate

**Comment by LeanKhan** [comment]
The remove button is for new candidate fields you add not the old ones. It should only show for the new fields.

**Comment by danieliheonu** [comment]
After you create an election and you click on edit, you'll see a delete button and remove button. The delete button removes the candidate from the db while the remove button only removes the input field

**Comment by LeanKhan** [comment]
Yes, that is the purpose. But it should only show first candidate fields that are not in the db yet

**Comment by danieliheonu** [comment]
Oh I get. So they can remove the field in case they mistakenly added an extra field. 
Okay then. 
Good job bro
